# Generated by Django 5.0 on 2025-10-04 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_petition_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='petition_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
